#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

open --new /Applications/Utilities/Terminal.app $DIR/MoOS
#echo $DIR/MoOS \"$DIR/\";
open "http://127.0.0.1:8080";
#COMMAND=$($DIR/MoOS "$DIR")

